"""add inventory adjustment log table

Revision ID: 3791e7e3ee49
Revises: d8e5d38e78c4
Create Date: 2025-12-03 09:52:56.399070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3791e7e3ee49'
down_revision: Union[str, None] = 'd8e5d38e78c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_adjustment_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_id', sa.UUID(), nullable=False),
    sa.Column('old_quantity', sa.Integer(), nullable=False),
    sa.Column('new_quantity', sa.Integer(), nullable=False),
    sa.Column('adjusted_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adjusted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['partner_allocated_inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_adjustment_logs_adjusted_by'), 'inventory_adjustment_logs', ['adjusted_by'], unique=False)
    op.create_index(op.f('ix_inventory_adjustment_logs_inventory_id'), 'inventory_adjustment_logs', ['inventory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_adjustment_logs_inventory_id'), table_name='inventory_adjustment_logs')
    op.drop_index(op.f('ix_inventory_adjustment_logs_adjusted_by'), table_name='inventory_adjustment_logs')
    op.drop_table('inventory_adjustment_logs')
    # ### end Alembic commands ###
