"""add carrier column to shipments table

Revision ID: 42bb5e628149
Revises: 7bc1fd719c05
Create Date: 2025-12-02 20:22:55.007601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42bb5e628149'
down_revision: Union[str, None] = '7bc1fd719c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('carrier', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'carrier')
    # ### end Alembic commands ###
