"""Add cancellation and refund fields to Order model

Revision ID: 6a373c9d8be8
Revises: 9a11da260b0b
Create Date: 2025-12-02 10:19:58.623472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a373c9d8be8'
down_revision: Union[str, None] = '9a11da260b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cancellation_status', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('cancellation_requested_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('refund_status', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('refund_reason', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('refund_requested_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'refund_requested_at')
    op.drop_column('orders', 'refund_reason')
    op.drop_column('orders', 'refund_status')
    op.drop_column('orders', 'cancellation_requested_at')
    op.drop_column('orders', 'cancellation_reason')
    op.drop_column('orders', 'cancellation_status')
    # ### end Alembic commands ###
