"""Rename Order.status to payment_status and set shipping_status default to preparing

Revision ID: 6a4e51fc136f
Revises: 3a48f2f0eb7c
Create Date: 2025-12-01 15:25:28.539211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a4e51fc136f'
down_revision: Union[str, None] = '3a48f2f0eb7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
