"""add_user_table_and_link_fulfillment_partners

Revision ID: 7bc1fd719c05
Revises: 6a373c9d8be8
Create Date: 2025-12-02 15:18:01.314377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc1fd719c05'
down_revision: Union[str, None] = '6a373c9d8be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.add_column('fulfillment_partners', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'fulfillment_partners', ['user_id'])
    op.create_foreign_key(None, 'fulfillment_partners', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fulfillment_partners', type_='foreignkey')
    op.drop_constraint(None, 'fulfillment_partners', type_='unique')
    op.drop_column('fulfillment_partners', 'user_id')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
