"""add affiliate user relationship and click payment tables

Revision ID: d8e5d38e78c4
Revises: 42bb5e628149
Create Date: 2025-12-02 21:41:34.068258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e5d38e78c4'
down_revision: Union[str, None] = '42bb5e628149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_clicks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affiliate_id', sa.UUID(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_clicks_affiliate_id'), 'affiliate_clicks', ['affiliate_id'], unique=False)
    op.create_table('affiliate_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affiliate_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_payments_affiliate_id'), 'affiliate_payments', ['affiliate_id'], unique=False)
    op.add_column('affiliates', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_affiliates_user_id'), 'affiliates', ['user_id'], unique=True)
    op.create_foreign_key('fk_affiliates_user_id', 'affiliates', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_affiliates_user_id', 'affiliates', type_='foreignkey')
    op.drop_index(op.f('ix_affiliates_user_id'), table_name='affiliates')
    op.drop_column('affiliates', 'user_id')
    op.drop_index(op.f('ix_affiliate_payments_affiliate_id'), table_name='affiliate_payments')
    op.drop_table('affiliate_payments')
    op.drop_index(op.f('ix_affiliate_clicks_affiliate_id'), table_name='affiliate_clicks')
    op.drop_table('affiliate_clicks')
    # ### end Alembic commands ###
