"""Add Inquiry model for unified inquiry system

Revision ID: f3a8b954df0c
Revises: e5a2c3b4d6f9
Create Date: 2025-12-03 15:49:11.022462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a8b954df0c'
down_revision: Union[str, None] = 'e5a2c3b4d6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inquiry_type', sa.String(length=50), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('reply_to_email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiries_created_at'), 'inquiries', ['created_at'], unique=False)
    op.create_index(op.f('ix_inquiries_inquiry_type'), 'inquiries', ['inquiry_type'], unique=False)
    op.create_index(op.f('ix_inquiries_reply_to_email'), 'inquiries', ['reply_to_email'], unique=False)
    op.create_index(op.f('ix_inquiries_sender_id'), 'inquiries', ['sender_id'], unique=False)
    op.create_index(op.f('ix_inquiries_status'), 'inquiries', ['status'], unique=False)
    op.alter_column('settings', 'profit_per_unit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('settings', 'marketing_commission_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True)
    op.alter_column('settings', 'shipping_commission_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True)
    op.drop_column('settings', 'affiliate_commission_rate')
    op.drop_column('settings', 'paypal_fee_rate_avg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('paypal_fee_rate_avg', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('affiliate_commission_rate', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True))
    op.alter_column('settings', 'shipping_commission_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False)
    op.alter_column('settings', 'marketing_commission_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False)
    op.alter_column('settings', 'profit_per_unit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_index(op.f('ix_inquiries_status'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_sender_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_reply_to_email'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_inquiry_type'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_created_at'), table_name='inquiries')
    op.drop_table('inquiries')
    # ### end Alembic commands ###
